# Generated by Django 3.0.8 on 2020-07-14 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleNewClass',
            fields=[
                ('regn', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50, unique=True)),
                ('Faculty', models.CharField(max_length=50)),
                ('Date', models.DateField(default=datetime.date(2020, 1, 1))),
                ('Time', models.TimeField(default=datetime.time(2, 30, 5))),
                ('Fee', models.FloatField()),
                ('Duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_register',
            fields=[
                ('regno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
