# Generated by Django 3.0.8 on 2020-07-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App02', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulenewclass',
            name='Duration',
            field=models.IntegerField(verbose_name=200),
        ),
        migrations.AlterField(
            model_name='schedulenewclass',
            name='Fee',
            field=models.FloatField(max_length=90000),
        ),
        migrations.AlterField(
            model_name='student_register',
            name='password',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student_register',
            name='user',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
