# Generated by Django 3.0.8 on 2020-07-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App02', '0002_auto_20200716_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulenewclass',
            name='Duration',
            field=models.IntegerField(max_length=200),
        ),
    ]
