# Generated by Django 3.0.8 on 2020-07-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App02', '0003_auto_20200716_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulenewclass',
            name='Duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_register',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
