# Generated by Django 3.0.8 on 2020-07-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App02', '0004_auto_20200716_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_register',
            old_name='password',
            new_name='pas',
        ),
    ]
